// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAApQsqpZlHTJHgsEQYgjzqcTjMkkV6CEA',
    appId: '1:930302853058:web:151d1e6d3f5ed1b937e05b',
    messagingSenderId: '930302853058',
    projectId: 'scrutineering-app',
    authDomain: 'scrutineering-app.firebaseapp.com',
    storageBucket: 'scrutineering-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChqofXUfN_9jIpOMRZINXfwsWYG91xyeY',
    appId: '1:930302853058:android:f04dcab7d42da95e37e05b',
    messagingSenderId: '930302853058',
    projectId: 'scrutineering-app',
    storageBucket: 'scrutineering-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-0z32jPFq1m8H6P4EJGxBmVLWx8jytbk',
    appId: '1:930302853058:ios:3c69e13481dda86137e05b',
    messagingSenderId: '930302853058',
    projectId: 'scrutineering-app',
    storageBucket: 'scrutineering-app.firebasestorage.app',
    iosBundleId: 'com.example.pitCheck',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-0z32jPFq1m8H6P4EJGxBmVLWx8jytbk',
    appId: '1:930302853058:ios:3c69e13481dda86137e05b',
    messagingSenderId: '930302853058',
    projectId: 'scrutineering-app',
    storageBucket: 'scrutineering-app.firebasestorage.app',
    iosBundleId: 'com.example.pitCheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAApQsqpZlHTJHgsEQYgjzqcTjMkkV6CEA',
    appId: '1:930302853058:web:b903408ab6b685a037e05b',
    messagingSenderId: '930302853058',
    projectId: 'scrutineering-app',
    authDomain: 'scrutineering-app.firebaseapp.com',
    storageBucket: 'scrutineering-app.firebasestorage.app',
  );
}
